object FrCellChart: TFrCellChart
  Left = 0
  Top = 0
  Width = 320
  Height = 240
  DragKind = dkDock
  DragMode = dmAutomatic
  TabOrder = 0
  object HotGrafPanel: TPanel
    Left = 0
    Top = 0
    Width = 320
    Height = 240
    Align = alClient
    BevelOuter = bvLowered
    UseDockManager = False
    DragKind = dkDock
    DragMode = dmAutomatic
    TabOrder = 0
    object FloatChart: TChart
      Left = 1
      Top = 42
      Width = 318
      Height = 197
      BackWall.Brush.Color = clWhite
      BackWall.Brush.Style = bsClear
      Gradient.EndColor = 16444045
      Gradient.Visible = True
      MarginTop = 5
      Title.Text.Strings = (
        'TChart')
      Title.Visible = False
      BottomAxis.DateTimeFormat = 'dd.MM.yy'
      BottomAxis.LabelsFont.Charset = DEFAULT_CHARSET
      BottomAxis.LabelsFont.Color = clTeal
      BottomAxis.LabelsFont.Height = -11
      BottomAxis.LabelsFont.Name = 'Arial'
      BottomAxis.LabelsFont.Style = []
      BottomAxis.LabelStyle = talValue
      BottomAxis.StartPosition = 1.000000000000000000
      BottomAxis.EndPosition = 99.000000000000000000
      LeftAxis.Automatic = False
      LeftAxis.AutomaticMinimum = False
      LeftAxis.LabelsFont.Charset = DEFAULT_CHARSET
      LeftAxis.LabelsFont.Color = clRed
      LeftAxis.LabelsFont.Height = -11
      LeftAxis.LabelsFont.Name = 'Arial'
      LeftAxis.LabelsFont.Style = []
      LeftAxis.StartPosition = 2.000000000000000000
      LeftAxis.EndPosition = 97.000000000000000000
      LeftAxis.Title.Caption = 'Value 1'
      LeftAxis.Title.Font.Charset = DEFAULT_CHARSET
      LeftAxis.Title.Font.Color = clRed
      LeftAxis.Title.Font.Height = -11
      LeftAxis.Title.Font.Name = 'Arial'
      LeftAxis.Title.Font.Style = []
      Legend.Visible = False
      RightAxis.Automatic = False
      RightAxis.AutomaticMinimum = False
      RightAxis.LabelsFont.Charset = DEFAULT_CHARSET
      RightAxis.LabelsFont.Color = clBlue
      RightAxis.LabelsFont.Height = -11
      RightAxis.LabelsFont.Name = 'Arial'
      RightAxis.LabelsFont.Style = []
      RightAxis.StartPosition = 2.000000000000000000
      RightAxis.EndPosition = 97.000000000000000000
      RightAxis.Title.Angle = 90
      RightAxis.Title.Font.Charset = DEFAULT_CHARSET
      RightAxis.Title.Font.Color = clBlue
      RightAxis.Title.Font.Height = -11
      RightAxis.Title.Font.Name = 'Arial'
      RightAxis.Title.Font.Style = []
      View3D = False
      OnAfterDraw = FloatChartAfterDraw
      Align = alClient
      UseDockManager = False
      TabOrder = 0
      OnMouseMove = FloatChartMouseMove
      object Series13: TLineSeries
        Marks.ArrowLength = 8
        Marks.Visible = False
        SeriesColor = 8388863
        Pointer.InflateMargins = True
        Pointer.Style = psRectangle
        Pointer.Visible = False
        Stairs = True
        XValues.DateTime = True
        XValues.Name = 'X'
        XValues.Multiplier = 1.000000000000000000
        XValues.Order = loAscending
        YValues.DateTime = False
        YValues.Name = 'Y'
        YValues.Multiplier = 1.000000000000000000
        YValues.Order = loNone
      end
      object Series14: TLineSeries
        Marks.ArrowLength = 8
        Marks.Visible = False
        SeriesColor = 16744448
        VertAxis = aRightAxis
        Pointer.InflateMargins = True
        Pointer.Style = psRectangle
        Pointer.Visible = False
        Stairs = True
        XValues.DateTime = False
        XValues.Name = 'X'
        XValues.Multiplier = 1.000000000000000000
        XValues.Order = loAscending
        YValues.DateTime = False
        YValues.Name = 'Y'
        YValues.Multiplier = 1.000000000000000000
        YValues.Order = loNone
      end
    end
    object Panel1: TPanel
      Left = 1
      Top = 1
      Width = 318
      Height = 41
      Align = alTop
      Color = clMoneyGreen
      TabOrder = 1
      DesignSize = (
        318
        41)
      object GName: TLabel
        Tag = 10000000
        Left = 1
        Top = 1
        Width = 316
        Height = 13
        Align = alTop
        Alignment = taCenter
        Caption = 'Name'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clMaroon
        Font.Height = -11
        Font.Name = 'MS Sans Serif'
        Font.Style = []
        ParentFont = False
        Transparent = True
      end
      object LVal: TLabel
        Left = 168
        Top = 16
        Width = 19
        Height = 13
        Caption = 'LVal'
        Color = clYellow
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clOlive
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentColor = False
        ParentFont = False
        ParentShowHint = False
        ShowHint = False
        Transparent = True
        Visible = False
      end
      object cbTu: TCheckBox
        Left = 304
        Top = 24
        Width = 17
        Height = 17
        Anchors = [akTop, akRight]
        Checked = True
        State = cbChecked
        TabOrder = 0
        OnClick = cbTuClick
      end
    end
  end
  object Timer1: TTimer
    Enabled = False
    OnTimer = Timer1Timer
    Left = 16
    Top = 40
  end
end
